name: On Push CI
on:
  push:
    branches:
      - development
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant rights
        run: ls && chmod +x android/build.gradle && chmod +x android/gradlew
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - name: Install dependencies
        run: npm install
      - name: Decrypt keystore
        run: cd android/app && gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.KEYSTORE_DECRYPT_PASSWORD }}" --output ./carend-upload.keystore carend-upload.keystore.gpg && cd ../../
      - name: Setup gradle.properties
        run: mkdir -p ~/.gradle/ && echo '${{ secrets.GRADLE_PROPERTIES }}' > ~/.gradle/gradle.properties
      - name: Build Release AAB
        id: buildRelease
        run: cd android && ./gradlew assembleRelease
      - name: Upload AAB
        id: uploadArtifact  
        uses: actions/upload-artifact@v1
        with:
            name: app-release.apk
            path: app/build/outputs/apk/release/app-release.apk
      - name: Notify on Slack
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
